### ISSUE TITLE
运行后显示聚星台

### ISSUE THREAD

**Issue by David1119** [fieteam/fie-toolkit-qnui#2]
页面没更新吧？怎么显示是聚星台？直接复制的fie-toolkit-blue？
另外问一下，桌面版qn-sdk可用么？完全找不到文档。。。
千牛的文档乱成一团了，什么qap、QAP-SDK、fie、QNUI、sui、react、rax、weex、jssdk。。。简直无力吐槽，能把文档好好写写吗？难道还是试验品？

**Comment by tao1587** [comment]
这....感觉没人在更新

**Comment by fattydevelop** [comment]
- 为什么显示聚星台？

> 这个只是demo的视觉样式本身和聚星台没有关系，你可以自行修改。

- 与fie-toolkit-blue的关系

> 两者使用底层技术栈是完全一致的，只是上层根据业务定制的UI库不同。分开做脚手架的原因是让开发者更快速的针对业务进行开发。

- 千牛目前确实缺少对技术栈的大图展示，从一个角度进入会感觉文档不连贯统一，我会持续推进这件事。

- 不是实验品，目前已经有多家ISV使用该套件进行业务开发并已上线。有具体的脚手架需求和bug反馈可以提ISSUE，会有人定期解决。
