### ISSUE TITLE
启动报错warning

### ISSUE THREAD

**Issue by q1457797371** [fieteam/fie-toolkit-qnui#4]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

 Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

报错2个警告，看着很讨厌，如何处理？

**Comment by fattydevelop** [comment]
这个是开发版本react的废弃提醒，生产环境中的react是没有警告的。
