### ISSUE TITLE
fie install toolkit-qnui 安装不了

### ISSUE THREAD

**Issue by Mssunny** [fieteam/fie-toolkit-qnui#7]
× Install fail! RequestError: connect ETIMEDOUT 100.67.95.39:80 (req "error"), GET http://registry.npm.alibaba-inc.com/@ali%2Ffie-toolkit-qnui -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":6,"createSocketErrorCount":0,"closeSocketCount":5,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.alibaba-inc.com:80:":1},"requests":{}})
headers: {}
Error: connect ETIMEDOUT 100.67.95.39:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
npminstall version: 3.2.1
npminstall args: C:\Program Files (x86)\nodejs\node.exe C:\Users\ww\AppData\Roaming\npm\node_modules\fie\node_modules\npminstall\bin\install.js @ali/fie-toolkit-qnui@latest --cwd=C:\Users\ww\.fie --registry=http://registry.npm.alibaba-inc.com/ --china --stdio=inherit
'tnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
[core-error] 安装 @ali/fie-toolkit-qnui@latest 出错,请确认网络是否正常及包名是否输入正确

**Comment by CharlieShine** [comment]
我也是同样的错误 , windows环境

**Comment by CharlieShine** [comment]
找到问题了 , 请使用
fie switch
命令切换内网和外网环境 , 不能使用内网环境

**Comment by LuckyDonkey** [comment]
原来是这样子，害我搞了半天，唉
